### ISSUE TITLE
你为什么不通过guestfs使用sed命令直接去替换shadow命令呢

### ISSUE THREAD

**Issue by luashiping** [xuriwuyun/change-root-passwd#1]
我使用了这个命令g.sh("sed -ir '/^root/s#root:([^:]+):(.*)#root:'"+sha512_password+"':\2#' /etc/shadow")去替换shadow文件，没报错，但是始终改不过来！如果可以的话，你的代码就不需要这么复杂了，呵呵

**Comment by luashiping** [comment]
你有时间可以试一下

**Comment by xuriwuyun** [comment]
你这个方法是可行的，可以省去read file、匹配字符串、write file环节代码。多谢！
这个命令之所以没生效，原因在于sed i 和r选项放一起执行会有问题，写成这样g.sh("sed -i -r '/^root/s#root:([^:]+):(.*)#root:'"+sha512_password+"':\2#' /etc/shadow")就可以了

**Comment by luashiping** [comment]
嗯！呵呵！
